### ISSUE TITLE
Speech: Multiple Lines

### ISSUE THREAD

**Issue by DroidPsychoPT** [GoogleCloudPlatform/python-docs-samples#1060]
## In which file did you encounter the issue?
python-docs-samples/speech/cloud-client/transcribe_streaming_mic.py

### Did you change the file? If so, how?
No, I did not change the file
![test](https://user-images.githubusercontent.com/19489372/29085241-3d6ef96e-7c5e-11e7-886c-07317ebe4514.png)

## Describe the issue

When reaching the end of the line, the python program copies the line and pastes it for each word that stays in the phrase in the second line.

**Comment by jonparrott** [comment]
@dizcology can you take a look?

**Comment by jerjou** [comment]
Heh - this is actually a known issue. Turns out the way that I'm overwriting interim results is by printing a carriage return and just printing over it. Unfortunately, terminals interpret carriage returns to move the cursor just to the beginning of the line. So when the transcript takes up more than one line, it'll only start overwriting on the last line.

I couldn't think of how to do this Correctly without having to bring in a heavy-weight library like ncurses or something, so I left it as-is. I figured, as a demo it works as-is, and I figured the sample wouldn't be used for exactly that purpose anyway.

Open to suggestions, but I suspect we can't fix this without making the sample a lot more heavyweight.
