### ISSUE TITLE
Django tutorial for App Engine is broken

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/python-docs-samples#10653]
The section in the [following App Engine quickstart](https://cloud.google.com/python/django/appengine#database_connection)  references a variable in the code `USE_CLOUD_SQL_AUTH_PROXY` that only works locally and not when deploying to App Engine.

```python
# Use django-environ to parse the connection string
DATABASES = {"default": env.db()}

# If the flag as been set, configure to use proxy
if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
    DATABASES["default"]["HOST"] = "127.0.0.1"
    DATABASES["default"]["PORT"] = 5432
```

The flag sets the host and port of the database connection to expect a local TCP connection. This works for the local deployment of the app as the quickstart prompts the user to run the Cloud SQL Auth Proxy locally configured with TCP.

However, if this flag is set when deploying the code to App Engine it breaks the sample. App Engine is automatically configured with the Cloud SQL Auth Proxy but the Proxy in a serverless environment is configured to use Unix sockets not a TCP connection.

The `.env` file used in the quickstart sets the database connection to use the proper Unix socket configuration (`/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME`) [in a previous step](https://cloud.google.com/python/django/appengine#create-django-environment-file-as-a-secret).
```sh
echo DATABASE_URL=postgres://DATABASE_USERNAME:DATABASE_PASSWORD@//cloudsql/PROJECT_ID:REGION:INSTANCE_NAME/DATABASE_NAME > .env
```

However, the use of the `USE_CLOUD_SQL_AUTH_PROXY` flag overrides this proper value and breaks the sample.

Noted by a SO user: https://stackoverflow.com/questions/77164817/django-app-on-google-app-engine-not-connecting-to-google-cloud-sql/77172777

**Comment by glasnt** [comment]
> if this flag is set when deploying the code to App Engine it breaks the sample.

Correct. The `USE_CLOUD_SQL_AUTH_PROXY` flag would break in prod, but it should never be set in prod. 

---

Per the [proxy docs](https://cloud.google.com/sql/docs/postgres/connect-instance-auth-proxy), setting up the proxy to `./cloud-sql-proxy INSTANCE_CONNECTION_NAME` yields `Listening on 127.0.0.1:5432 for INSTANCE_CONNECTION_NAME`.

The helper package in this deployment, [`django-environ`](https://django-environ.readthedocs.io/en/latest/), allows you to use a `.env` file to load environment variables. This is useful when there are many variables that need to be loaded.  The `env.db()` helper method also allows you to set a database connection string (`DATABASE_URL`), rather than separate configurations for username, password, host, etc., splitting them up and setting them in the `DATABASE[default]` setting. 

Therefore, when using the local proxy, the hostname changes. In this sample, the `USE_CLOUD_SQL_AUTH_PROXY` flag is used to help make those changes to the `DATABASE`, specifically changing the `HOST` and `PORT`. 

Setting `USE_CLOUD_SQL_AUTH_PROXY` as an environment variable in the local terminal shouldn't affect App Engine. The only way I can see this might have happened is if `USE_CLOUD_SQL_AUTH_PROXY` ended up in the `.env`, and was therefore in play in production. 

Unless I'm otherwise misunderstanding the problem, this sample works as intended.

**Comment by jackwotherspoon** [comment]
@glasnt I find the naming of `USE_CLOUD_SQL_AUTH_PROXY` variable quite confusing and it seems users are also finding it confusing.

If I was reading [this section of the docs](https://cloud.google.com/python/django/appengine#database_connection), it does not explicitly mention that the var should only be set for using the Proxy with a local TCP connection.

The section says "If you set the `USE_CLOUD_SQL_AUTH_PROXY`, the DATABASES setting is changed to infer use of the Cloud SQL Auth Proxy." which is not 100% accurate (setting the env var to False infers a Unix socket connection with the Cloud SQL Auth Proxy). If I am a new user reading this and wanting to use the Cloud SQL Auth Proxy with App Engine I would assume I need to set the env var to True. 

I wonder if we can maybe make this env var more clear for users. Really the env var is for toggling between Unix vs TCP connection type for the Cloud SQL Auth Proxy.

**Comment by glasnt** [comment]
After discussion with @jackwotherspoon, I'll update the Understanding the Code - Database connection description to better reflect what this setting is doing in local setups.
