### ISSUE TITLE
Python Scripts for New VmWare Engine Standard Network

### ISSUE THREAD

**Issue by harman93singh** [GoogleCloudPlatform/python-docs-samples#10979]
Hi , 

We have been trying to Create VmWare Engine Network using Google Created Python Functions 
`vmwareengine/cloud-client/create_legacy_network.py`

It seems this supports Legacy Network Creation Only, tried deploying STANDARD Network using the same function updating the below line  of code 
` network.type_ = vmwareengine_v1.VmwareEngineNetwork.Type.STANDARD`
but it fails , reason being not supported. 

Could you please help us with Python code supporting New Standard VMWare Engine Network creation . 

thank you

**Comment by dandhlee** [comment]
Hi there. This repository is for issues related to Python samples in this repository.

Please file an issue on https://github.com/googleapis/google-cloud-python/issues - since it's a different org I can't move the issue unfortunately. The code exists in https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-vmwareengine.
