### ISSUE TITLE
How to change google ocr model?

### ISSUE THREAD

**Issue by Hyeoghwan** [GoogleCloudPlatform/python-docs-samples#11125]
Here is my code 

```
from google.cloud import vision
client = vision.ImageAnnotatorClient()
with open(...) as f:
  content = f.read()
image = vision.Image(content=content)
response = client.document_text_detection(image=image)
```

I have to get the same format of the document_text_detection method. and have to change the model to test. 
from "builtin/stable" to "builtin/latest"

I tried like that. 
```
vision.ImageAnnotatorClient.Feature.model = "builtin/latest"
client = vision.ImageAnnotatorClient()
```

But it doesn't seem to work. 
from what I have searched for,  change the reqeust is the one way to do that. 
like, 

```
image = vision.Image(content=content)
feature = vision.Feature(type=vision.Feature.Type.TEXT_DETECTION, model="builtin/latest")
request = vision.AnnotateImageRequest(image=image, features=[feature])

...

ocr_text_obj = self.client.annotate_image(request, retry=self.google_retry, timeout=timeout_sec)
``` 

but, the return format of the self.client.annotate_image is not what I want. 
So, I just want to change the feature and to use document_text_detection. How to do that?

**Comment by m-strzelczyk** [comment]
I'm afraid it's not possible to use features with `client.document_text_detection`. This method is a convenience added to the client, that simplifies calling image annotation when you want only single feature. It is hardcoded to call `annotate_image` with a single feature with default values.

If you're interested, it's implemented through `add_single_feature_methods` decorator in [`google/cloud/vision_helpers/decorators.py`](https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-vision/google/cloud/vision_helpers/decorators.py).

I'm afraid you will have to use the `annotate_image` method with `AnnotateImageRequest` object to use the non-default models. 

However, I fail to understand why the `annotate_image` result is not what you want, since both `annotate_image` and `document_text_detection` both return `AnnotateImageResponse` object. If it's the content of the response you don't like, perhaps that's coming from the fact that you use different model?
