### ISSUE TITLE
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid audio content: too long.)>

### ISSUE THREAD

**Issue by Jfeng3** [GoogleCloudPlatform/python-docs-samples#1152]
## In which file did you encounter the issue?

transcribe_streaming.py

## Describe the issue
FLAC file 
Duration: 00:00:30.00, start: 0.000000, bitrate: 192 kb/s
    Stream #0:0: Audio: flac, 16000 Hz, mono, s16

## Error 
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid audio content: too long.)>

**Comment by jonparrott** [comment]
@gguuss @jerjou could one of you take a look?

**Comment by jerjou** [comment]
Hello-

Can you provide more detail? What are you doing, exactly? You mention you're using `transcribe_streaming.py`. Did you remember to modify it to specify that the file you're transcribing is FLAC, rather than LINEAR16? Also, if you just have a file that you're looking to transcribe, you should probably not be using the streaming endpoint - that one expects you to be streaming the audio to it in realtime (for things like, streaming audio from your microphone). If you just want to transcribe a file, it's faster and easier to use either `transcribe.py` or `transcribe_async.py.`

**Comment by bjohas** [comment]
@jerjou I may have a similar problem. Does the "google.api_core.exceptions.InvalidArgument: 400 Request payload size exceeds the limit: 10485760 bytes." also apply to files accessed via GCS URIs / gs:// ?

In principle, for files accessed via GCS URI, is there a time limitations? (We'd like to transcribe files that are about an hour long.)

**Comment by engelke** [comment]
The API and libraries have had significant updates since this report, and are passing tests. The issue may have resolved itself for that reason. If not, please reopen this issue.
