### ISSUE TITLE
Why there are two requirements files in Django GAE example?

### ISSUE THREAD

**Issue by eyalev** [GoogleCloudPlatform/python-docs-samples#1362]
## In which file did you encounter the issue?

appengine/standard/django/requirements-vendor.txt
appengine/standard/django/requirements.txt

## Describe the issue

In the Django GAE example, why there is a `requirements.txt` file **and** `requirements-vendor.txt` ?

**Comment by jonparrott** [comment]
See https://cloud.google.com/python/django/appengine

One is used for running locally, one is used to prepare dependencies when deploying to GAE.

**Comment by Li-ReDBox** [comment]
I know this is an old and closed thread but it fits to me a bit better instead of asking in another question. Feel free to move this thread to a proper place.

I have a code base shared between multiple GAE services. They have different requirements.txt. What I have found out is that `gcloud app deploy` does not support `-r another-requirements.txt` based on my test (only requirements.txt is copied?). I cannot recall symlink worked either. Can we ask `gcloud app deploy` to use a specific requirements.txt? 

Thanks
