### ISSUE TITLE
Django Postgres on GoogleCloud Platform

### ISSUE THREAD

**Issue by rose888** [GoogleCloudPlatform/python-docs-samples#1482]
I tried to follow the instruction here to set up the Django Postgres env on google  flex env: 
 https://cloud.google.com/python/django/flexible-environment.  But I keep on getting the error below.  and on the database side, I see the error "couldn't connect INSTANCE-NAME".

File "/home/julie/python-docs-samples/appengine/flexible/django_cloudsql/env/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

**Comment by gakeseaton** [comment]
You'll need to keep the cloud sql proxy running in the background, and update the settings file so that your Django application connects to the PostgreSQL instance via the proxy on localhost when not in production on GAE. Here is the relevant line in [settings.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/a07a09a2cdbcde938e58b9764708931d0fa6798e/appengine/flexible/django_cloudsql/mysite/settings.py#L101)

**Comment by engelke** [comment]
See July 16 comment above.
