### ISSUE TITLE
Issue with tensorflow dependency 

### ISSUE THREAD

**Issue by megretson** [GoogleCloudPlatform/python-docs-samples#1521]
Hello! I am new to the google app engine, and I have been fighting for a few days with an issue in deploying a basic flask app I've made. The application I've made requires keras, and therefore tensorflow, both of which I have placed in a lib folder in the root directory of my project. However, whenever I attempt to deploy the application, I receive the following error: 

Beginning deployment of service [default]...
ERROR: (gcloud.app.deploy) Cannot upload file [...../lib/tensorflow/python/_pywrap_tensorflow_internal.so], which has size [156707700] (greater than maximum allowed size of [33554432]). Please delete the file or add to the skip_files entry in your application .yaml file and try again.

I can't fathom there is no way for me to use tensorflow, so I've got to be doing something else wrong. I'd be happy to attach the source for the project I'm working on if that would be useful as well. I'd really appreciate any help or suggestions!

**Comment by engelke** [comment]
App Engine Standard Environment for Python 2.7 has several limits that seem to prevent using Tensorflow. Those limits are mostly gone using the Standard Environment for Python 3.7, but there is still an issue because Tensorflow does not support Python 3.7 at this time.

Your options would be to use App Engine Flexible Environment, or a different Compute service, such as Compute Engine.
