### ISSUE TITLE
Unable to get OpenID Connect token in IAP sample code

### ISSUE THREAD

**Issue by caxton** [GoogleCloudPlatform/python-docs-samples#1731]
## In which file did you encounter the issue?

GoogleCloudPlatform/python-docs-samples/iap/iap_test.py

### Did you change the file? If so, how?

- change command from "GOOGLE_CLOUD_PROJECT=iap-sample **pytest** iap_test.py" to "GOOGLE_CLOUD_PROJECT=iap-sample **python** iap_test.py" because _-bash: pytest: command not found_

- remove "from gcp_devrel.testing.flaky import flaky" and "@flaky" because _ImportError: No module named 'gcp_devrel'_

- update **REFLECT_SERVICE_HOSTNAME** and **IAP_CLIENT_ID** based on the real value in project _iap-sample_

## Describe the issue

1. create a project _iap-sample_
2. create a service account _local-test-account_ in project _iap-sample_
3. deploy app_appengin_app to project _iap-sample_
4. ensure I can get JWT header from _iap-sample.appspot.com_
5. turn on IAP and add service account created in step 2 in the IAP white list
6. run GOOGLE_CLOUD_PROJECT=**iap-sample python** iap_test.py
7. always get below exception
```
Traceback (most recent call last):
  File "iap_test.py", line 50, in <module>
    test_main()
  File "iap_test.py", line 40, in test_main
    IAP_CLIENT_ID)
  File "/github/python-docs-samples/iap/make_iap_request.py", line 49, in make_iap_request
    raise Exception('make_iap_request is only supported for service '
Exception: make_iap_request is only supported for service accounts.
```

Does the sample code really work or I did anything wrong?

**Comment by engelke** [comment]
First, if you want to run the full tests, you need to install the requirements in the testing folder, as well as the sample folder. So, if you are in the iap folder, you'd need

```
pip install -r requirements.txt
pip install -r ../testing/requirements.txt

```
That should solve the missing module issues you had at first.

Second, the error message you got is because the first command in `make_iap_request` that gets credentials is not getting them for a service account, but (probably) from your own Google account. Download a key file for the service account you want (from the IAM/Service Accounts page in the console) to a `.json` file, then set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to point to that file and try again. There may still be problems, but this should get you further along.
