### ISSUE TITLE
Google Speech TCP socket on client hangs on CLOSE_WAIT 

### ISSUE THREAD

**Issue by ashwini-venkatesh** [GoogleCloudPlatform/python-docs-samples#1831]
While using the streaming recognize method of google speech, the API fails to provide an interface which can close the TCP sockets opened by the client. All the connections open to the sockets are in CLOSE_WAIT state. This in turn leads to overflow of file descriptors if many calls are made to the speech API over time.

Sample output of `lsof -i -a -p 14142 | wc -l` where 14142 is the PID of the process which calls the Speech API.
```
1004u  IPv4 278882958      0t0  TCP 10.0.0.83:33800->sfo03s08-in-f13.1e100.net:https (CLOSE_WAIT)
 1005u  IPv4 278913383      0t0  TCP 10.0.0.83:59004->sfo03s01-in-f205.1e100.net:https (CLOSE_WAIT)
 1006u  IPv4 278883240      0t0  TCP 10.0.0.83:33860->sfo03s08-in-f13.1e100.net:https (CLOSE_WAIT)
1007u  IPv4 279010856      0t0  TCP 10.0.0.83:36442->sfo03s01-in-f205.1e100.net:https (CLOSE_WAIT)
```

**Comment by nnegrey** [comment]
I'm running our infinite streaming sample and not seeing these results after the request and responses are all processed. 

I only see the bi-directional sockets at a time. 

Would need the steps to reproduce to know how this was caused. Closing for now, but feel free to re-open if this is still an issue, thought it might be more of a libraries, rather than samples issue.

**Comment by ChristianVermeulen** [comment]
@ashwini-venkatesh I would love to know if this was finally resolved eventually. Especially how 😅 .
