### ISSUE TITLE
Update calls to encode and decode for KMS documentation

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/python-docs-samples#1848]
## In which file did you encounter the issue?

kms/api-client/asymmetric.py

### Did you change the file? If so, how?

```
@@ -62,8 +62,8 @@ def decryptRSA(ciphertext, client, key_path):
                     .asymmetricDecrypt(name=key_path,
                                        body=request_body)
     response = request.execute()
-    plaintext = base64.b64decode(response['plaintext'])
-    return plaintext
+    plaintext = response.get('plaintext', None)
+    return base64.b64decode(plaintext) if plaintext else None
# [END kms_decrypt_rsa]
 @@ -108,7 +108,8 @@ def signAsymmetric(message, client, key_path):
                     .asymmetricSign(name=key_path,
                                     body={'digest': digest_JSON})
     response = request.execute()
-    return base64.b64decode(response.get('signature', None))
+    signature = response.get('signature', None)
+    return base64.b64decode(signature) if signature else None
# [END kms_sign_asymmetric]
```

## Describe the issue

The original code for decoding isn't correct because `base64.b64decode()` fails if given `None`:
```
response = request.execute()
return base64.b64decode(response.get('signature', None))  # Fails on the fallback of "None"
```

This change returns `None` if the expected response parameter isn't present for encoding and decoding.

**Comment by engelke** [comment]
Per the REST and Python library documentation, the call to execute will return a well-formed response or else raise an exception. This sample does not handle exceptions, but passes them on to the caller to handle.

The code for getting the signature (that uses response.get) should never fall-back to returning None. In fact, there is no reason to not just use response['signature'] since an exception will occur before this line if the call to execute fails.

PR #1886 removes the use of .get, making sign and decrypt consistent.
