### ISSUE TITLE
Postgres example for AppEngine Standard  Python 3.7 uses pg8000 instead of psycopg2

### ISSUE THREAD

**Issue by checor** [GoogleCloudPlatform/python-docs-samples#2154]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/postgres/sqlalchemy/main.py

## Describe the issue

According to the documentation here: https://cloud.google.com/appengine/docs/standard/python3/using-cloud-sql

Shows this example that uses psycopg2 as the SQLalchemy driver for GAE Standard Python 3.7: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/cloudsql/main_postgres.py

But, in the the file that I encountered the [issue](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/postgres/sqlalchemy/main.py), the example uses pg8000.

Also, the documentation in this page shows MySQL code, instead of the intended Postgres example: https://cloud.google.com/sql/docs/postgres/connect-app-engine

What is the recommended approach to use Postgres with App Engine?

Cheers!

**Comment by wTylerReid** [comment]
+1 on this.  Conflicting documentation is a huge headache

**Comment by kurtisvg** [comment]
You should be able to use either driver. The samples mentioned above are just examples, and don't reflect a specific choice or recommendation.

I've double checked the Connecting from App Engine page and the postgres sample is displayed correctly, so the issue must have already been correct since this was opened.
