### ISSUE TITLE
composer - broken DAG with 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by smsalaken** [GoogleCloudPlatform/python-docs-samples#2164]
## In which file did you encounter the issue?

python-docs/sample/composer/workflow/bq_copy_across_locations.py

### Did you change the file? If so, how?

No

## Describe the issue
I was trying to copy two BigQuery Public dataset from US region to Sydney. Followed instructions from https://cloud.google.com/blog/products/data-analytics/how-to-transfer-bigquery-tables-between-locations-with-cloud-composer with the exceptions of changing the name and disk size (30 GB instead of default value) in workers.

Changed airflow variable `table_list_file_path` to  `home/airflow/gcs/dags/bq_copy_us_to_aus.csv`. It was `bq_copy_eu_to_us_sample.csv` in the instructions. Both the python and csv files exist in the DAG folder in GCS. The airflow variables showed up properly in `airflow web UI > admin > variables`. 

However, the airflow web UI homepage shows the following error:
`Broken DAG: [/home/airflow/gcs/dags/bq_copy_across_locations.py] 'NoneType' object is not iterable`.

No DAG is available for trigger as well.

**Comment by pujoljuliaessence** [comment]
Hi there,

I've got the same issue. Could you please advise?

**Comment by leahecole** [comment]
I'm going to try to replicate this issue - @pujoljuliaessence if you can give me more details about the steps you took so I can see if they're similar to @smsalaken that would be awesome. (Were you also going from US to Sydney? Did you also use a 30 GB machine?)

**Comment by leahecole** [comment]
Alright - I've been able to replicate this issue. This error - 'NoneType' object is not iterable - occurs when there is code that is trying to loop through an object that is of type 'None'. In this DAG, there are two spots where things loop:

1) In `read_table_list` when the code reads through the CSV
2) In the DAG where it says `for record in all_records` - it's trying to loop through the output of read_table_list. 

The way I was able to duplicate this issue was by putting a typo in the `table_list_file_path` parameter value. This results in the "Broken DAG" error as well as the DAG being unavailable for trigger. 

Please double check that the file specified in `table_list_file_path` matches up with the file you're using.

**Comment by leahecole** [comment]
I'll be closing this issue for now, but please feel free to reopen if you need further help and provide as much detail as you can and are comfortable with sharing to help us help you.
