### ISSUE TITLE
Server not sending data to devices : end_to_end_example

### ISSUE THREAD

**Issue by matthewmarion** [GoogleCloudPlatform/python-docs-samples#2176]
I followed this quickstart guide by Google: https://cloud.google.com/iot/docs/samples/end-to-end-sample. 

Everything is connected and seems to be working fine; however, my server is not instructing devices to turn their fans on/off. Also, whenever I run the device command twice on one device, the command which was executed first should stop, but this isn't happening either.

I am running my devices on --mqtt_bridge_port=443. This is the only change I made from the tutorial. I have no errors & my subscription is on the list of subscriptions for my topic.

Any idea would be appreciated.

**Comment by gguuss** [comment]
There was an issue around mid-may with the port from Google Cloud, there's a chance this was the cause. Can you try again and let us know if you're still seeing the issue?

If this doesn't work, try pulling the subscription using the [Google Cloud SDK](https://cloud.google.com/sdk):
```
gcloud pubsub subscriptions pull <your-subscription-name>
```

You could check that the sample is successfully connecting by using state messages instead of telemetry. Then you can see the state in the [Google Cloud Console](https://console.cloud.google.com/iot). 

Change [this line](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py#L228) to be `state` instead of `events`.

Hopefully this helps you isolate what's going on.

**Comment by gguuss** [comment]
@matthewmarion Let me know if the issue is still persisting.
