### ISSUE TITLE
IAP Authentication Samples are incomplete

### ISSUE THREAD

**Issue by zmunro** [GoogleCloudPlatform/python-docs-samples#2422]
## In which file did you encounter the issue?
python-docs-samples/iap/make_iap_request.py

### Did you change the file? If so, how?
No

## Describe the issue

There is no information in this example about WHEN/HOW/WHERE to call these functions. The code is referenced on this page of google's documentation:
https://cloud.google.com/iap/docs/authentication-howto#iap_make_request-php

It states: "The following sample code authenticates the default service account to a Cloud IAP-secured resource"

But in the examples (Python is the one I am dealing with), all the code does is define two functions. It doesn't say anything about how to use these functions.

I am trying to follow the guide here:
https://cloud.google.com/run/docs/events/pubsub-push
And it says: "If you are using Cloud Run for Anthos deployed on GKE, you must verify the identity within the container. See the Cloud IAP sample code that demonstrates this."
So I am trying to verify the identity of my service account from within the container but I have no idea how!!

**Comment by andrewferlitsch** [comment]
@engelke PTAL

**Comment by engelke** [comment]
The document is focused on how to make a request that a managed service (such as App Engine with IAP, Cloud Functions, or Cloud Run) will allow to pass through to the application code. In those cases, the application does not need to authenticate the incoming request, since the platform already did that.

For other applications, such as those running on Compute Engine or GKE, incoming requests will be passed to the application without verifying that they are authenticated, and the application itself needs to perform that verification. The web page states this: "If you are using Cloud Run for Anthos on Google Cloud, you must verify the identity within the container." However, the link shows how to create an authenticated request, not how to verify one that the application is consuming.

The receiving application needs to verify the token in the Authorization: Bearer header. Python sample code that can do this is the validate_iap_jwt_from_compute_engine function in the file at https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iap/validate_jwt.py.
