### ISSUE TITLE
Infinite streaming is_final often does not = True when it should

### ISSUE THREAD

**Issue by bbookman** [GoogleCloudPlatform/python-docs-samples#2440]
**is_final** is not getting set to True when it should.  A large amount of transcription text never makes it to the **is_final** stage.

python-docs-samples/speech/microphone/transcribe_streaming_infinite.py
I modified the code in transcribe_streaming_infinite.py with only a few statements to write to a file and write "FINAL" or "NOT FINAL" in the result.is_final clause.

To make it super easy to see any is_final, the following code was added:
`        if result.is_final:
            with open(results_file, 'a') as file:
                file.write('\n ======================================== \n')
                file.write('\n    IS_FINAL = TRUE\n')
                file.write('\n ======================================== \n')
`

I tried two audio files here: https://www.dropbox.com/sh/p3bgbjt7i7l3s3o/AACHH4fgLDblzH6psz7Q1nRsa?dl=0

- ruts1.wav
- me2.m4a

The results are also in that dropbox folder:
- ruts1_results.txt
- me2_results.txt

### ruts1.wav
I played this through the speaker on my phone while my Mac ran transcribe_streaming_infinite.py.

Although the transcript starts at 0 here:
**0**: NEW REQUEST
**1510** NOT FINAL: did I

Notice the first FINAL stamp in the results happens here:
**86230** FINAL: play statistics and that is delightful but it's not for us to run Victory laps because despite the fact that we've made you an improvement and despite the fact they were significantly better than the national average be like today

### me2.m4a
Audio was captured by me speaking into the Mac microphone.

Here also, audio stream starts at 0:
0: NEW REQUEST
**1190** NOT FINAL: all right

The first FINAL stamp happens here:
**83110** FINAL: and talking and to my microphone while running this python script and really talking about nothing in particular so that we get a good test case

In both cases above, you can see from the captured results and the NOT FINAL stamps that a good amount of transcribed text does not get finalized.

This is my code (with txt extension so that it uploads)
[transcribe_streaming_infinite_modified.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/files/3692554/transcribe_streaming_infinite_modified.txt)

I'm told by others that this is reproducible in the java sample for infinite streaming as well as from a customer doing their own C# implementation

**Comment by nnegrey** [comment]
Is this an issue with the samples themselves or the backend api?

**Comment by nnegrey** [comment]
The `transcribe_streaming_infinite.py` sample has a Streaming limit of 10 seconds, although the api can handle 5 minutes, not sure why that was done. 

But because of that, the behavior that will result is that a new client gets opened every 10 seconds.

We close the old one and don't wait for the response, but we resend the audio to make sure we get a final transcription. 
So you'll have some non-final transcription lost in the middle because we're switching over to a new client and resending that "lost" audio. 

The `transcribe_streaming_indefinite.py` sample doesn't do as much work, simply opens a new connection and so you may not get the `is_final` flag because the stream was closed and a new one was opened. 

If this is something important, you can add your own streaming management layer to only close a stream once all is_final messages have been sent or catch the error when the limit is hit.
