### ISSUE TITLE
Pub/Sub: reformat code to follow style guide

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/python-docs-samples#2599]
In a recent #2555, `black` introduced format changes that don't conform to Google's style guide. 
- Use single quotes instead of double quotes
- etc. 

Please update the code in the Pub/Sub subdirectory so they are standardized across the entire repo.

**Comment by andrewferlitsch** [comment]
@anguillanneuf PTAL

**Comment by anguillanneuf** [comment]
@andrewferlitsch I haven't looked it this issue for some while. 

Do you know what's the magic formatting command(s) to allow all samples to 1) pass all lint tests 2) conform to all formatting style guide?

**Comment by leahecole** [comment]
I'm going to close this for now because right now, `black` is the best thing we have for auto-formatting, and pub/sub passes lint regularly, so I am not too worried. However, if you do notice that lint rules look off in the noxfile-template, please let me know. I know @gguuss had a lot of opinions about the style when #2555 first came around, but given that we have not come up with a better solution between the time this issue was opened and now, I don't think it's worth leaving this open. Happy to be contradicted with good reason though, Tianzi! :)
