### ISSUE TITLE
Can not connect to postgres Server from Kubernete instance.

### ISSUE THREAD

**Issue by ThanhTuNguyen** [GoogleCloudPlatform/python-docs-samples#2619]
Recently, my Kubernetes instance can not connect into PSQL, i don't know why. I didn't touch on this server in a couple of months. Does something has changed since that time? Can someone point for me out? Do i need to update something?

Thanks.

https://imgur.com/uWHMATG

**Comment by ThanhTuNguyen** [comment]
Hi there, any update about my case ? I really want to deploy my project using this technique!

**Comment by ThanhTuNguyen** [comment]
I know this is the holiday, but you guys should leave some comments to address those issues. We still pay money for this service and need a stable version for a real project out there. I think if this is a bug, someone would fix it asap or people will find another technology

**Comment by busunkim96** [comment]
@ThanhTuNguyen Apologies for the delay in replying. If you have a support contract with Google, please reach out via https://cloud.google.com/support/.

This repository is primarily for filing issues related to sample code.

**Comment by busunkim96** [comment]
There is some general guidance about connecting to PostgreSQL from Kubernetes in this guide: https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

**Comment by kurtisvg** [comment]
Hi @ThanhTuNguyen,

To reiterate what @busunkim96 said, this repo is for python samples and not general support. If you have a support contact, please reach out via the support link provided. If not, consider posting your issue to StackOverflow for help debugging the problem. 

If you think the issue is with your Cloud SQL instance, you can open an issue via our [Public Issue Tracker](https://issuetracker.google.com). If you think the issue is with the Cloud SQL proxy, you can open the issue on the [proxy's repo](https://github.com/GoogleCloudPlatform/cloudsql-proxy).
