### ISSUE TITLE
Unable to import 'google.appengine.ext'pylint(import-error)

### ISSUE THREAD

**Issue by 101361-s** [GoogleCloudPlatform/python-docs-samples#2966]
## In which file did you encounter the issue?

I encoutered the issue in the appengine_config.py. Honestly, I was just following the [google tutorial ](https://cloud.google.com/appengine/docs/standard/python/getting-started/python-standard-env)and [this one ](https://www.freecodecamp.org/news/how-to-build-a-web-application-using-flask-and-deploy-it-to-the-cloud-3551c985e492/)
## Describe the issue

It was unable to import 'google.appengine.ext' from vendor. i looked at the sdk file i downloaded and I couldn't find it there.

**Comment by busunkim96** [comment]
Hi @101361-s. Can you confirm that you are using App Engine in the Python 2 Standard Environment? I believe that specific import will not be available in other versions.

**Comment by 101361-s** [comment]
I'm sorry? I don't understand.

**Comment by andrewsg** [comment]
In your app.yaml file, does it say "runtime: python27" or does the runtime line say something else? Also, did you encounter this error on your own computer (in local development), or after running "gcloud app deploy"?

**Comment by 101361-s** [comment]
it says runtime:python27. i saw the error on my own computer and when i deployed it, it crashed because of it.

**Comment by andrewsg** [comment]
Thank you for the clarification. Can you please copy/paste the exact error message and traceback?

**Comment by 101361-s** [comment]
Unable to import 'google.appengine.ext'


appengine/standard/flask/tutorial/appengine_config.py

**Comment by andrewsg** [comment]
Thanks again. I think I need more information to understand what exactly has happened here. Can you copy and paste the entire terminal input and output, starting with the command you ran that produced this error on the command line, and ending with the full traceback as it appears on the terminal? Please redact anything private such as your project name.

**Comment by engelke** [comment]
I was unable to reproduce the exact error message reported, possibly due to minor changes in the App Engine environment. But I **was** able to get an error that I suspect is due to the same cause.

`google.appengine.ext` is automatically included in App Engine standard for Python 2.7, so either this was some kind of one-time glitch, or the problem happened when the library was used, not just imported. The only thing `google.appengine.ext` is used for in the `appengine/standard/flask/tutorial` sample is making the libraries in the `lib` directory available for import. The `appengine_config.py` file has the lines that do this:

```
from google.appengine.ext import vendor
vendor.add('lib')
```

For those lines to work, you must have a directory called `lib` in the directory that contains the `appengine_config.py` file with the needed libraries installed in it. That's created with the command `pip install -t lib -r requirements.txt`. The tutorial you mentioned does include this step, but it's easy to miss, so maybe it was not run before deployment.

Without much more detailed information on the error, this is the best I can diagnose this error and suggest a fix. If this does not help, please feel free to reopen this issue.
