### ISSUE TITLE
BatchPredict could not start due to empty input CSV file.

### ISSUE THREAD

**Issue by tc64** [GoogleCloudPlatform/python-docs-samples#3111]
## In which file did you encounter the issue?

python3.7/site-packages/google/cloud/automl_v1/gapic/prediction_service_client.py

### Did you change the file? If so, how?
no

## Describe the issue

Says CSV file is empty, but it is not. Please see below...

#### Environment details

1. AutoML Natural Language batch predict (google.cloud.automl_v1.gapic.prediction_service_client.PredictionServiceClient.batch_predict)
2. Ubuntu 16.04
3. 3.7.5
4. 
google-api-core==1.16.0
google-auth==1.11.0
google-cloud-automl==0.10.0
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0

#### Steps to reproduce

  1. basically this: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/automl/cloud-client/batch_predict.py

#### Code example

```python
logging.info("Make batch prediction")
    
    # Get the full path of the model.
    model_full_id = prediction_client.model_path(
        project, location, model_id
    )
    
    gcs_source = automl.types.GcsSource(input_uris=[input_path])

    input_config = automl.types.BatchPredictInputConfig(gcs_source=gcs_source)
    gcs_destination = automl.types.GcsDestination(output_uri_prefix=output_path)
    output_config = automl.types.BatchPredictOutputConfig(
        gcs_destination=gcs_destination
    )

    response = prediction_client.batch_predict(
        model_full_id, input_config, output_config
    )
    
    params = {"model_id":model_id,
             "model_full_id":model_full_id,
             "gcs_source":gcs_source,
             "input_config":input_config,
             "gcs_destination":gcs_destination,
             "output_config":output_config,
             "input_path":input_path,
             "output_path":output_path}
    
    logging.debug(params)

    logging.debug("Waiting for operation to complete...")
    logging.info("Batch Prediction results saved to Cloud Storage bucket. {}".format(response.result()))
```
Above, `prediction_client` is a `google.cloud.automl_v1.PredictionServiceClient`

#### Stack trace
```
DEBUG:root:Waiting for operation to complete...
DEBUG:google.api_core.retry:Retrying due to , sleeping 0.9s ...
Traceback (most recent call last):
  File "/home/tc/ml_experiments_plus1/call_segmentation/batch_predict.py", line 113, in <module>
    batch_predict(prediction_client, project_id, compute_region, model_id, input_path, output_path)
  File "/home/tc/ml_experiments_plus1/call_segmentation/batch_predict.py", line 41, in batch_predict
    logging.info("Batch Prediction results saved to Cloud Storage bucket. {}".format(response.result()))
  File "/home/tc/anaconda3_7/envs/ml_experiments_plus1/lib/python3.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.GoogleAPICallError: None BatchPredict could not start due to empty input CSV file.
```
The CSV file is not empty, I've tried with a few. The bucket is in us central 1. 

Thanks!

**Comment by nnegrey** [comment]
Which AutoML product are you using?

**Comment by Tum86** [comment]
I want to do a batch prediction and use the code as described in the documentation.
`project_id = "photovoltaicclassifier"
model_id = "TEN8533967251122946048"
input_uri = "gs://pv_patents/entity_batch_prediction.jsonl"
output_uri = "gs://pv_patents/"

prediction_client = automl.PredictionServiceClient()


model_full_id = f"projects/{project_id}/locations/us-central1/models/{model_id}"

gcs_source = automl.GcsSource(input_uris=[input_uri])

input_config = automl.BatchPredictInputConfig(gcs_source=gcs_source)
gcs_destination = automl.GcsDestination(output_uri_prefix=output_uri)
output_config = automl.BatchPredictOutputConfig(gcs_destination=gcs_destination)

response = prediction_client.batch_predict(
    name=model_full_id, input_config=input_config, output_config=output_config
)

print("Waiting for operation to complete...")
print(
    f"Batch Prediction results saved to Cloud Storage bucket. {response.result()}"
)`

My JSONL-File looks like the attachment
[entity_batch_prediction.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/files/8445460/entity_batch_prediction.txt)

Since this method worked great for document classification, I didn't expect any difficulties now. However, I now receive the following error message:

`GoogleAPICallError                        Traceback (most recent call last)
<ipython-input-7-3bc382f3b219> in <module>
     21 print("Waiting for operation to complete...")
     22 print(
---> 23     f"Batch Prediction results saved to Cloud Storage bucket. {response.result()}"
     24 )

~\anaconda3\lib\site-packages\google\api_core\future\polling.py in result(self, timeout, retry)
    135             # pylint: disable=raising-bad-type
    136             # Pylint doesn't recognize that this is valid in this case.
--> 137             raise self._exception
    138 
    139         return self._result

GoogleAPICallError: None BatchPredict could not start due to empty input CSV file.`

Especially I wonder about the reference to the CSV file, because I have a JSON file as input.
