### ISSUE TITLE
[dlp] inspect_content_test.py::test_inspect_datastore is potentially broken

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/python-docs-samples#3422]
The following tests are potentially broken:

dlp/inspect_content_test.py::test_inspect_datastore
dlp/inspect_content_test.py::test_inspect_datastore_no_results

Once merged, #3420 will fix the timeout issue on our builds.

#3420 also will make a change for the test behavior. Previously, these tests are trying to check if the [callback function](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b221fbfc16c39b1a624ca227bd58f12c5c411614/dlp/inspect_content.py#L649) in the sample has been called as expected.

Previous assertion:
```python
assert "Info type: EMAIL_ADDRESS" in out
```

Current assertion:
```python
assert "Inspection operation started" in out
```

As far as I tried, the callback was never called even with timeout of 420 seconds. That's why the test is now only checking if the operation was successfully started.

It's great if we can do the following:
1) debug why the callback is not called
2) test if the callback is called again

@andrewsg Do you have any insight? I'm asking because you're the original author.

**Comment by andrewsg** [comment]
Sorry for the delay. The only insight I have right now is that all of the pubsub callback functionality has been tempermental, at best, for as long as I've used the API. It was difficult to get it to work in the first place, in particular because there's no real visibility into why the callback wouldn't happen or what's happening on the remote host. Sorry I can't be more help =(

**Comment by tmatsuo** [comment]
I fixed another issues in `risk_test.py` with #3919 

Maybe we can do similar thing to make it work again.
