### ISSUE TITLE
IoT Gateway sample does not include storing and processing

### ISSUE THREAD

**Issue by abhideodhar-coder** [GoogleCloudPlatform/python-docs-samples#3579]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/mqtt_example/gateway_demo.py

### Did you change the file? If so, how?

No

## Describe the issue
The gateway documentation https://cloud.google.com/iot/docs/how-tos/gateways
talks about how gateway devices performs tasks including "storing and processing data". However, the sample MQTT gateway example does not show how exactly this can be done. The gateway server seems to be simply collecting the event from the edge device and publishing it to the cloud core - there is no storing of this message or processing of this message (apart from the forwarding).

Is there another example that demonstrates this functionality? Or any example of how this step can be done?

Thanks

**Comment by busunkim96** [comment]
@gguuss Could you take a look?

**Comment by gguuss** [comment]
Thanks for the heads up @busunkim96 !

The "storing and processing" of the data is performed in PubSub not on the device. For an example of this take a look at [the end-to-end sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py#L145-L183).

**Comment by abhideodhar-coder** [comment]
@gguuss - Thanks for the reply. 

However, I feel that the gateway should support "storing and processing event" functionality. 
a) For example - If the gateway does not support storing of events, then how can we handle error conditions such as if the gateway looses network connectivity with the IoT Core or if the gateway code crashes due to some software/hardware bug? In such scenarios, it will lead to loss of events from the device.
b) Another use case for processing events may be if the gateway is connected to hundreds of devices (with numerous video streams as an example) -  the network bandwidth may not be sufficient to forward everything to the IoT core. If the gateway can process some of these streams and filter out certain events before sending it up to the cloud, then it may be better in terms of the network bandwidth.

Thoughts?

**Comment by gguuss** [comment]
These are great scenarios but the primary goal of this sample is to concisely demonstrate the functionality that Google provides so that people building supported solutions can start here and tailor the code to their needs and understand the base functionality of our APIs and services. To add message caching to the sample would make an already lengthy section of code longer, further distracting from the goal of demonstrating the main concepts of Cloud IoT Core.

Additional features that could make sense in the sample include creating UIs, Event notification systems, message filtering, OTA and so on. To provide this functionality may also give a false sense that this code is a readily deployable solution when it's not and supporting this sample as a production-ready solution with feature engineering is not possible at this time.

Which leads me to a few suggestions for more comprehensive solutions that you __can__ integrate that offer more sophisticated (and supported) management of Edge data and provide support for and build on top of our platform:

* [Mongoose OS](https://medium.com/google-cloud/gps-cellular-asset-tracking-using-google-cloud-iot-core-firestore-and-mongooseos-4dd74921f582)
* [Linux Foundation Fledge](https://www.lfedge.org/projects/fledge/)
* [Zephyr OS](https://www.zephyrproject.org/)
* [Google Cloud IoT Device SDK for Embedded C](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/)

I've reclassified this as a feature request, should we start adding this level of functionality to the sample, we'll prioritize a more comprehensive gateway sample.

**Comment by sgreenberg** [comment]
I believe this question has been addressed well. Please feel free to reopen if you disagree.
