### ISSUE TITLE
[composer] Triggering Cloud Storage doesnt work

### ISSUE THREAD

**Issue by 3a3** [GoogleCloudPlatform/python-docs-samples#3732]
## In which file did you encounter the issue?

- [Triggering DAGs (workflows) | Cloud Composer | Google Cloud](https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#triggering-with-gcf-creating-a-function-python)
- [functions/composer/composer_storage_trigger.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/composer/composer_storage_trigger.py)
### Did you change the file? If so, how?

fix it on https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3731

## Describe the issue

I am challenging cloud composer tirggering cloud storage, but it doen't work with the following error message.

It looks changed on [iap/make_iap_request.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iap/make_iap_request.py).

```sh
Exception: Bad response from application: 400 / {'Date': 'Mon, 11 May 2020 05:42:10 GMT', 'Content-Type': 'application/json', 'Content-Length': '116', 'Server': 'gunicorn/19.10.0', 'Via': '1.1 google', 'Alt-Svc': 'h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'} / '{"error":"Run id manual__2020-05-11T05:42:10+00:00 already exists for dag id composer_sample_trigger_response_dag"}\n'
at
make_iap_request (/user_code/main.py:141)
at
trigger_dag (/user_code/main.py:61)
```

**Comment by leahecole** [comment]
Hi - I appreciate you opening this issue and submitting a PR. I'm not ready to merge it though because I'm having trouble replicating this error and want to understand a little bit more first. I have some questions:

1. When does this error occur? (During cloud function deployment, when you press "test the function", when you trigger it with a GCS update, or is the error in the DAG?)
2. Can you copy and paste your code, but remove any personal information like your client ID and Airflow tenant project?


@arithmetic1728 - I know that you updated the code in [iap/make_iap_request.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/iap/make_iap_request.py) since I last updated [functions/composer/composer_storage_trigger.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/composer/composer_storage_trigger.py) and it's completely possible something is out of date. Would you also be willing to take a look to see if something jumps out?

**Comment by arithmetic1728** [comment]
@leahecole functions/composer/composer_storage_trigger.py has a copy of iap/make_iap_request.py code (in the section between `# START COPIED IAP CODE` and `# END COPIED IAP CODE`), and it is not updated. This PR updates that code and looks fine to me.

I am not sure what caused the 400 error. The new make_iap_request.py code fetches id_token from metadata server instead of using IAM signer.

**Comment by 3a3** [comment]
> 1. When does this error occur? (During cloud function deployment, when you press "test the function", when you trigger it with a GCS update, or is the error in the DAG?)

When I put the object on GCS, this error occured in  [Testing your function](https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#triggering-with-gcf-creating-a-function-python) section. 
400 error in the Cloud Functions logs, not in Airflow DAGs.
![image](https://user-images.githubusercontent.com/4263027/81759115-c2dba500-94fe-11ea-862c-e7d292d41bbd.png)


And I found my mistake on [Creating your function](https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#triggering-with-gcf-creating-a-function-python) section.
So I forgot **Enable Retry on failure**. Now it still disable but it works.

> 2. Can you copy and paste your code, but remove any personal information like your client ID and Airflow tenant project?

I just copied the tutorial code from this repo. Only changed `client_id` and `webserver_id`.

**Comment by damianohienmhen** [comment]
@3a3 I have a similar problem while attempting to trigger my cloud composer DAG using a Cloud function. I get the same response, Bad response from application. How did you fix your code? I used the exact same code provided by Google Cloud but it still gives me that error.

**Comment by Omar-BenMohammed** [comment]
Hello @damianohienmhen
I'm facing the same issue as you when creating a cloud function to trigger a DAG. Could you please tell me how you managed to resolve it?

**Comment by damianohienmhen** [comment]
@Omar-BenMohammed  I don't think I had a solution with this problem. I was waiting for a response but never received it.
