### ISSUE TITLE
Restrict noxfile 

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/python-docs-samples#3801]
Currently we allow importing of a pytest.ini:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/noxfile-template.py#L148-L159

we should restrict that to only let users ignore certain folders instead

**Comment by tmatsuo** [comment]
FYI, I'll rollback that change with #3810 

It turned out that, if you have `pytest.ini` in the project directory, it will be used. So regardless of what our `noxfile-template.py` is doing, users can customize the behavior.

**Comment by tmatsuo** [comment]
@kurtisvg Do you still want to restrict the use of `pytest.ini`? There are some legitimate use cases for adding some options like #3854

**Comment by kurtisvg** [comment]
I do agree that this seems like a legitimate use case. I still have a slight preference that we still:
1) create some rule/guidelines about what is okay to configure and what shouldn't be
2) possible merge this into the noxfile config to avoid having multiple different files to tweak

But I don't feel very strongly about either, so if you would prefer to close this feel free.

**Comment by tmatsuo** [comment]
Although I understand the idea, 2 is too expensive to implement because if there's a `pytest.ini` file in the sub directory, it will be just picked up as a config. To achieve this, we need to remove `pytest.ini` from the sub project directory, and implement a filter which turns your config into `pytest.ini` file or pytest flags.

This is not intuitive and confusing if people ever try to add their own `pytest.ini` file (There was actually 0 `pytest.ini` in the repo added by people other than me).

**Comment by tmatsuo** [comment]
I think 1) sounds like a good idea, so maybe you can add some guide to `AUTHORING_GUIDE.md`?
