### ISSUE TITLE
Image Upload Issue using gcs Upload Signed URL | React JS

### ISSUE THREAD

**Issue by qaisershehzad** [GoogleCloudPlatform/python-docs-samples#3861]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/storage_generate_upload_signed_url_v4.py#L27

## Describe the issue
I have generated upload signed url using this function "generate_upload_signed_url_v4" as mentioned above and also I tried using GSUTIL as well using 
`gsutil signurl -m PUT service_account.json gs://<bucket>/file.png
`
I am working on a demo where I need to upload PDF, PNG to GCS bucket. File uploading is file. But when I preview file in GCS Storage Console  and download/preview file form Link URL	
PDF is fine. But PNG somehow got damaged and not opening/previewing.
I am using Chrome '81.0.4044.138'

When I further preview PNG file using text editor it contains some header content at the top of file.
i.e 
`------WebKitFormBoundarysZ3BDVaNOhqwENsp
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png
`
So if we remove this from top of file the file will open fine.. File is attached as well
![test (4)](https://user-images.githubusercontent.com/11673425/82643191-8c9dd400-9c28-11ea-84fe-d854ac2979e6.png)

I have created a sample React project which can be accessed here 
**Demo: https://github.com/qaisershehzad/upload-gcs**
I am using this code for file upload
`
    const url = "https://storage.googleapis.com/<bucket>/file.png.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gitlab-ci%<Project>.iam.gserviceaccount.com%2F20200521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20200521T175304Z&X-Goog-Expires=36000&X-Goog-SignedHeaders=content-type%3Bhost&X-Goog-Signature=<Signature>"

    const data = new FormData()
    data.append('file', this.state.selectedFile)

    var xhr = new XMLHttpRequest();

    xhr.open('PUT', url, true);
    xhr.setRequestHeader("Content-type", "application/octet-stream");
    

    xhr.onload = function (response) {
      console.log('on-load', response);
    };

    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {

        if (xhr.status === 200) {
          console.log("Status OK")

        } else {
          console.log("Status not 200")
        }
      }
    };

    xhr.onerror = function (response) {
      console.log("Response error", response)
    };

    xhr.upload.onprogress = function (evt) {
      // For uploads
      if (evt.lengthComputable) {
        var percentComplete = parseInt((evt.loaded / evt.total) * 100);
        console.log("progress", percentComplete)

      }
    }
    xhr.send(data);`

I also tried same thing on Android as well and facing same issue. In Png at top these header string got added which not allowing to open Png file.

Png uploading is working fine using this CURL request.
curl -X PUT -H 'Content-Type: application/octet-stream' --upload-filen file.png 'https://storage.googleapis.com/<bucket>/file.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gitlab-ci%<Project>.iam.gserviceaccount.com%2F20200521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20200521T175304Z&X-Goog-Expires=36000&X-Goog-SignedHeaders=content-type%3Bhost&X-Goog-Signature=<Signature>'

It will be helpful if you can help to resolve this issue.

**Comment by qaisershehzad** [comment]
Can someone help to resolve this issue ? As I am bit stuck and not able to resolve this issue. This is also happening on Android as well.

**Comment by qaisershehzad** [comment]
Instead of sending FormData if I send file directly it works fine. So there is some issue with FormData when Image file uploaded it appends some headers to file.
In cURL direct file is posted so it is working.

`    xhr.send(this.state.selectedFile);`

**Comment by frankyn** [comment]
Hi @qaisershehzad, I know you've been waiting for some time and hopefully you can still chime in.

IIUC, the issue is that FormData represents an HTML form while you are using a Signed URL to upload contents of your image which means the body of the request will send a multipart body which *is not* what you want.

I recommend reading the file into memory bypassing FormData and then calling:

`xhr.send(filedata);`

An alternative is to use Post Policy which provides you with information for FormData which is then handled by the Cloud Storage API:
https://cloud.google.com/storage/docs/xml-api/post-object#usage_and_examples

**Comment by qaisershehzad** [comment]
@frankyn  thanks for your reply. 
Yes, I am using  `xhr.send(filedata);` and it is working fine for me.

**Comment by MOIN-AKHTAR** [comment]
Hello everyone i'm using nodejs and reactjs.On my nodejs backed i'm able to get signedUrl but using this signedUrl and sending a large file into chunks to the sessionUrl which i'm getting when i'm hitting post request using signedUrl which i got from my nodejs backend things are not working properly.I have discussed this issue here:
https://github.com/googleapis/nodejs-storage/issues/1990
But not got any solution yet.
