### ISSUE TITLE
Python flex template argparser

### ISSUE THREAD

**Issue by adsee42** [GoogleCloudPlatform/python-docs-samples#4308]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dataflow/flex-templates/streaming_beam/streaming_beam.py

## Describe the issue

According to this [official document](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#python), 

> Dataflow templates use runtime parameters to accept values that are only available during pipeline execution

but in the above file, arguments are parsed with python built-in `argparse`.

I'm confused about the right way to define arguments.

Or does that mean the `RuntimeValueProvider` and `parser.add_value_provider_argument()` way is the same with
```
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
```
way?

**Comment by davidcavazos** [comment]
It's a little confusing due to product names, but the [docs on creating templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#python) are for "regular templates", and those use the `ValueProvider` interfaces for inputs.

On the other hand, the code sample is from the [**Flex** templates](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) which allows to run a template from a Docker container, it allows for more customization and flexibility (I guess that's where the name came from). For flex templates, the `ValueProvider` interface is not used.

So "regular templates" and "flex templates" are two *different* ways of creating templates.

**Comment by davidcavazos** [comment]
I'm closing this but feel free to reopen if that didn't answer your question.
