### ISSUE TITLE
Where is the service account file stored?

### ISSUE THREAD

**Issue by sephethus** [GoogleCloudPlatform/python-docs-samples#4435]
Ref: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/054c726d5b147268170b202f6b7779b9329fa4b6/composer/workflows/kubernetes_pod_operator.py#L48

Where is this volume mounted? Where is this key stored? What is the context here? There's literally no info on this.  Our airflow runs in kubernetes, should it be in a worker pod?

**Comment by leahecole** [comment]
Hi @sephethus, thanks for opening an issue. I'm sorry you feel there is "literally no info". It's possible that that info is spread across a lot of places and is not well documented and that that needs to change. It's possible that the info you need isn't there. Both Airflow and Kubernetes are open source, and the folks behind it are only human, and that lack of info can be very frustrating. Thank you for your patience and understanding, especially given that it's 2020 and being a human in 2020 is hard. 

Let me share some additional info and context with you that may help: This code is part of a larger tutorial called [Using the KuberenetesPodOperator](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator) where there is some more information on using the different configs. Additionally, here's some more info about [using secrets as files from a pod](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod). Off the top of my head, I think that it should be in a worker pod, but without replicating your exact use case, I'm not 100% positive. I would also recommend taking a look at some [Airflow community resources](https://airflow.apache.org/community/) - in particular, searching for the word `secret` and/or `kubernetespodoperator` in the #airflow-gcp and #airflow-kubernetes channels in the [Apache Airflow Slack](https://apache-airflow-slack.herokuapp.com/). 

As you continue to debug, feel free to reopen this issue or create a new one, and be sure to include as much info as possible so that I can try to replicate your use case as closely as possible.

Lastly, if you feel this sample needs an update, we fully welcome contributions - I am only human, and I wrote this sample awhile ago, and it likely could benefit from a fresh set of eyes like yours! 

Best of luck, and hope to continue to see you within the Airflow community!
