### ISSUE TITLE
Cannot run speech streaming example now

### ISSUE THREAD

**Issue by abihc** [GoogleCloudPlatform/python-docs-samples#484]
I could run the all speech api examples without any error until this morning, however, I got an error when I ran speech_streaming.py:

```
Traceback (most recent call last):
  File "speech_streaming.py", line 157, in <module>
    main()
  File "speech_streaming.py", line 149, in main
    request_stream(stop_audio), DEADLINE_SECS))
  File "speech_streaming.py", line 125, in listen_print_loop
    for resp in recognize_stream:
  File "/home/chiba/.pyenv/versions/anaconda3-4.1.0/envs/gasr/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 153, in next
    return self._next()
  File "/home/chiba/.pyenv/versions/anaconda3-4.1.0/envs/gasr/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 147, in _next
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1472177364.848861732","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":1}")
```

I tried to run it both on Ubuntu 16.04 and on OS X Yosemite, but the result was same.

Does anyone know the solution for this?

**Comment by F324** [comment]
I have the same issue and same error message with  sample code as well as with my own program. 

Part of the error message:
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1472207486.837745000","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":1}")
E0826 12:31:27.196445000 140735186059264 chttp2_transport.c:1810] close_transport: {"created":"@1472207487.192932000","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"referenced_errors":[{"created":"@1472207487.192918000","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

Help! 
Otherwise, my demo  will be demolished!
Could someone please restart the speech service?

**Comment by jerjou** [comment]
Unfortunately, this isn't really the best place to report service-level issues (like this appears to be) - this issue tracker is for issues with the sample code itself, and while we do try to address whatever gets reported to us as we have opportunity (we too feel your pain), we're often not the best equipped for that sort of thing.

Anyway, it looks like the script runs as expected right now. In the future, you might try GCP's [support page](https://cloud.google.com/support/).
