### ISSUE TITLE
Minimum dependencies for building Google Cloud Platform GRPC Voice application

### ISSUE THREAD

**Issue by thecloudist** [GoogleCloudPlatform/python-docs-samples#532]
## For the voice-controlled robot car:

Going the k.i.s.s. route and building a simple app without any special packaging.
Will worry about sharing it once it is fully operational and bug-free. (:>

What are the **minimum dependencies required** to incorporate voice/grpc.methods into my application?

requirements.txt:

gcloud==0.18.1
grpcio==1.0.0
PyAudio==0.2.9
grpc-google-cloud-speech-v1beta1==1.0.1

transcribe_streaming_thread.py 

imports:

from gcloud.credentials import get_credentials
from google.cloud.speech.v1beta1 import cloud_speech_pb2 as cloud_speech
from google.rpc import code_pb2
from grpc.beta import implementations

Appreciate some guidance on this.

Cheers

**Comment by puneith** [comment]
@thecloudist Those are the requirements and dependencies required.

**Comment by thecloudist** [comment]
My problem is that when I run the virtualenv recommended in the README , I cannot access my RPi.GPIO module for some reason. I can access it outside of the VENV but not while in it.

I tried doing the pip install -r requirements.txt outside of the VENV but it fails at the very end with 👍 
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-XRkyiv/gcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5P5q2U-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-XRkyiv/gcloud
Storing debug log for failure in /home/pi/.pip/pip.log

And when I run a simple import test:

from transcribe_streaming_thread import *
  File "/home/pi/Awareness/Voice_Audio/SoundInput/transcribe_streaming_thread.py", line 24, in <module>
    from gcloud.credentials import get_credentials
ImportError: No module named gcloud.credentials

Was it a bad idea to run requirements.txt outside of the VENV?

Not sure how to get this working. Spent hours and could not resolve to get both of these services working in the same environment.

Was able to get the speech stuff fully running on the Pi as per the README but not with Raspberry PI libs for some reason.

**Comment by thecloudist** [comment]
FYI - I was able to pip install the missing Pi dependencies into the virtualenv so the two libs can play together. Pi and GCO/Speech/Grpc.

(yay)

**Comment by jerjou** [comment]
Yeah - the reason we recommend installing everything into a virtualenv is to try to avoid dependency conflicts, which will be different for different platforms. It's a general problem that doesn't have a great solution because it's so specific to different environments and situations; and the cleanest way to avoid it is to just start from a clean virtualenv.

That said, there's nothing about the requirements.txt that requires being run in a virtualenv. Installing outside of a virtualenv should be fine, but may run into dependency conflict issues, as you've observed. In principle, these should be resolvable, but in practice you end up spending way more time trying to resolve them than you want (as you've discovered ;) ).

Anyway, glad you were able to figure it out. If you'd like, you can read more about virtualenvs [here](https://virtualenv.pypa.io/en/stable/) and requirements.txt [here](https://pip.pypa.io/en/stable/user_guide/#requirements-files).
