### ISSUE TITLE
Is it possible to record and upload the transcriptions from _transcribe_streaming.py?

### ISSUE THREAD

**Issue by thetittenquetscher** [GoogleCloudPlatform/python-docs-samples#606]
When running `python transcribe_streaming.py`

the program freezes after I use the voice command “exit” . It keeps logging "Exiting..". Is this normal ?

<img width="562" alt="screen shot 2016-10-21 at 19 33 50" src="https://cloud.githubusercontent.com/assets/13262717/19609936/41230514-97da-11e6-87e8-0e9cc88874e3.png">

------------------------------------------------------------------------------

When the 60 seconds streaming limit is reached, is there a way to restart the  _transcribe_streaming.py_ automatically again ?

------------------------------------------------------------------------------

**Also can you record and upload the transcriptions from _transcribe_streaming.py_ to Google Cloud Storage or to my local hard drive ?**

------------------------------------------------------------------------------

Thank you for your attention.

**Comment by jerjou** [comment]
* Can you file a different issue for the "Exiting.." problem?
* As for the other two of your questions, keep in mind that this repo is a repo of sample code. You should feel free to modify it to add the functionality you'd like - the existing code is there mainly for illustration and education. For example
  * You could potentially create a [Timer object](https://docs.python.org/2/library/threading.html#timer-objects) that communicates with the main thread to restart the operation after 60 seconds. Granted - there are some tricky issues to deal with here, so I've got it on my todo list to write a sample that does this (as I mentioned [here](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/517#issuecomment-247663337))
  * Instead of just printing the response, you could open a [file object](https://docs.python.org/3/c-api/file.html) and write the responses to that file. Or you could upload it to cloud storage, modifying the code snippet [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/530ab8aaf446a4332b6b5e957581a7dda269e988/storage/cloud-client/snippets.py#L93) to use [`upload_from_string`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ec781b6e8afc0b27599ddc69848571e1abf412ff/storage/google/cloud/storage/blob.py#L586), once the audio has ended.

**Comment by thetittenquetscher** [comment]
Thank you for your input @jerjou .

Lets say transcribe_streaming.py transcribes the spoken sentence “ I am dreaming about pears  “  with 90.00 confidence. The word pear is listed in an array and triggers the transcribe_streaming.py to run another program which again starts a 10 seconds short video clip about falling pears from trees in slow motion. Could this be accomplished with the sample as well, when modified?

![aww-board 34](https://cloud.githubusercontent.com/assets/13262717/19615493/1c27203a-9800-11e6-808e-bff54049737d.png)

**Comment by jerjou** [comment]
Yup!
