### ISSUE TITLE
<_MultiThreadedRendezvous of RPC that terminated with status = StatusCode.ABORTE

### ISSUE THREAD

**Issue by TimurTarasenko** [GoogleCloudPlatform/python-docs-samples#7794]
I use Airflow and Google Bigtable.

I'm getting this issue when I try to run code in Airflow.

ERROR - <_MultiThreadedRendezvous of RPC that terminated with
	status = StatusCode.ABORTE
	details = "Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)
	debug_error_string = "{"created":"@1649868116.434085656","description":"Error received from peer ipv4:142.251.6.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)","grpc_status":10}
>
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 980, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/home/airflow/gcs/plugins/minutebardata.py", line 55, in execut
    tk.get_data(dt=self.dt
  File "/home/airflow/gcs/plugins/scraper/ticker.py", line 46, in get_dat
    df0 = self.dbhook._load_minubebar_tickers(ticker, start_dt, dtf
  File "/home/airflow/gcs/plugins/scraper/db_wrapper.py", line 568, in _load_minubebar_ticker
    dfs = [self.process(row, ticker) for row in rows if row is not None
  File "/home/airflow/gcs/plugins/scraper/db_wrapper.py", line 568, in <listcomp
    dfs = [self.process(row, ticker) for row in rows if row is not None
  File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 485, in __iter_
    response = self._read_next_response(
  File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 474, in _read_next_respons
    return self.retry(self._read_next, on_error=self._on_error)(
  File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_fun
    on_error=on_error
  File "/opt/python3.6/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_targe
    return target(
  File "/opt/python3.6/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 470, in _read_nex
    return six.next(self.response_iterator
  File "/opt/python3.6/lib/python3.6/site-packages/grpc/_channel.py", line 416, in __next_
    return self._next(
  File "/opt/python3.6/lib/python3.6/site-packages/grpc/_channel.py", line 803, in _nex
    raise sel
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with
	status = StatusCode.ABORTE
	details = "Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)
	debug_error_string = "{"created":"@1649868116.434085656","description":"Error received from peer ipv4:142.251.6.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Error while reading table 'projects/myproject/instances/dev-02/tables/mytable' : Response was not consumed in time; terminating connection.(Possible causes: slow client data read or network problems)","grpc_status":10}

 
I use the following approach

        row_set = RowSet()
        row_set.add_row_range_from_keys(
            start_key=ticker + b"#" + startdt,
            end_key=ticker + b"#" + enddt)

        rows = table.read_rows(
            row_set=row_set)
This code works properly when I run this locally. Could you give me any hints to find the solution?

**Comment by leahecole** [comment]
Hi! Is this from one of the samples located in the repo? And are you using Cloud Composer? If so, please point me to which sample! If not, I'd recommend asking on the [Airflow community Slack](https://airflow.apache.org/community/) (under "Ask a question") in the `#airflow-gcp` channel. (Tbh, not a bad idea anyways just to get more eyes on it!) 

A hint to help you debug though assuming you are using Composer - sometimes when Airflow says something has timed out, a more detailed error message may be hiding in the logs in Kubernetes or in Cloud Logging, possibly something relating to authentication or authorization (or not!) If you go to your environment in the Cloud Console and go to "Environment Configuration" you can click on "View Logs" next to "Cloud Logging". Within Cloud logging, I like to search for `Traceback`, which can sometimes reveal more of an error message. Another strategy is to go to your Kubernetes workloads in GKE and to examine the pod logs for an Airflow worker from there. The GKE approach isn't as easy when you have large environments and many tasks but if this is the only task you're running as you're debugging you might be able to find it. Those logs should be in Cloud Logging anyways though. 

And, a final word of wisdom - do make sure that this code is within the DAG object (the `with models.DAG(` part) and not outside so that it isn't parsed outside of DAG runs! 😄

**Comment by dandhlee** [comment]
Hey @TimurTarasenko, it seems that you've seen Leah's response so I'll mark this issue as closed. If you run into any further issues please feel free to reopen this issue and follow Leah's wisdom or open a new issue on here or the Airflow community Slack mentioned above.
