### ISSUE TITLE
Figure out a way to test App Engine code samples

### ISSUE THREAD

**Issue by jinglundong** [GoogleCloudPlatform/python-docs-samples#7906]
## In which file did you encounter the issue?

N/A

### Did you change the file? If so, how?

N/A

## Describe the issue

This is a follow up of https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7890. I believe the actual problem is more general - App Engine code samples don't have good test coverage.

**Comment by grayside** [comment]
The most direct solution would be to adapt the pattern of how Cloud Run samples are tested to App Engine: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/run/helloworld

Charlie, could you assess if the Cloud Run testing pattern might be adapted to App Engine? I expect some simplification because we do not need to pre-build the container image.

**Comment by jinglundong** [comment]
Right, seems like Cloud Run e2e test is using python's subprocess to start a gcloud command. We could do the same for GAE Standard, because they have the similar gcloud surface - `gcloud run deploy` vs. `gcloud app deploy`. 

A few ideas about the next steps:
* Decide if we want to run these e2e tests as "presubmit" which blocks the PR submission, or running periodically. I would vote for periodic run. 
* Look into if "presubmit" or periodic runs are supported by Github actions. https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
* Write the e2e test for App Engine Standard. We should be able to reuse most of the gcloud logic here https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/run/helloworld/e2e_test.py#L65-L84.

**Comment by grayside** [comment]
Test coverage needs to be both presubmit and periodic.

I defer to repo owners on CI choices. My understanding is Kokoro is the CI, but parcels of the testing could be run in Cloud Build, as long as the flaky test reporting is still supported.

**Comment by engelke** [comment]
I don't believe the legacy App Engine APIs from the Python 2.7 environment can be used outside of an App Engine instance. If I'm right, then we would have to deploy the samples to App Engine for the test. Since there's only one App Engine instance per project, I think we'd have a problem with parallel tests interfering with each other.

I'll explore whether I'm right about where those APIs can be called.

**Comment by jinglundong** [comment]
> I don't believe the legacy App Engine APIs from the Python 2.7 environment can be used outside of an App Engine instance.

Agree, I think it only makes sense to test them in the GAE environment. 

> Since there's only one App Engine instance per project, I think we'd have a problem with parallel tests interfering with each other.
Yes and no. Each GAE project could have multiple services (default to 5). Applications in each service is relatively independent. We have a couple of patterns for internal testing: 1) Use a pool of projects; tests rent projects from this pool randomly. 2) One designated project for one type of tests (e.g. all the datastore tests use the same project.)
