### ISSUE TITLE
volunteering to write a deployment guide

### ISSUE THREAD

**Issue by tstaerk** [GoogleCloudPlatform/python-docs-samples#8243]
I would appreciate a guide how to deploy these apps detailing what errors can happen. I volunteer to write it, already published a blog about it here: https://www.bingehacking.net/2022/08/appengine-hello-world.html

Is this something I can help with? Would you in turn explain me why it tries to install into the VPC named default?

**Comment by dandhlee** [comment]
Charlie, could you help take a look at this issue?

Hey @tstaerk, thank you for offering to help! Unfortunately we cannot accept brand new guides / samples. I really appreciate the gesture :)

**Comment by engelke** [comment]
I looked at the link and was surprised at the reported problems. Deploying this sample to an existing project should take no more than `gcloud app deploy`, as the README file says. So I tried it for myself, and didn't encounter those problems.

I don't know whether there problems were due to using an existing project that had some changes made since it was created, or some kind of environmental problem or transient glitch, but they don't seem to still happen. Given that, though we appreciate the suggestion, it doesn't seem needed at this time.

Thanks for the report and idea!
