### ISSUE TITLE
Found a possible security concern 

### ISSUE THREAD

**Issue by 7h3h4ckv157** [GoogleCloudPlatform/python-docs-samples#8314]
Hello Team! 

Previously I detailed a security bug in your code on 22nd August. Google bug hunter team acknowledged the case, I thought that might be the right place for reporting code-level security issues. So, my new findings also detailed recently on [g.co/vulnz](https://g.co/vulnz). (Regarding your policy). But after following the policy I get baffled by their reply. 

[![issue.png](https://i.postimg.cc/66bbqc4F/issue.png)](https://postimg.cc/G9YxSkQj)

I figure the new report was dealt with by someone not mindful of the policy and my past report was handled fine (acknowledged). In case I'm right, please make sure the GoogleVRP will accept code issues of this repository. 

Regards,

**Comment by dandhlee** [comment]
Hi there! Thanks for trying to file the issue.

If the problem is regarding a vulnerability in a code within this repository, as the name suggests they are supposed to be for Samples - code for educational purposes. That said, if this is a serious vulnerability we'll definitely take a close look to make sure they're taken care of, regardless of whether they are for samples that are not supposed to really be used for production environment. However, it seems that the vulnerability is not severe enough for it to have been escalated. If you think this is a mistake, please follow their instructions to let them know what the team might have missed out on.

You are still free to report the issue here where we'll make sure all of our code is not exploitable. For now, I'll mark this issue as resolved but feel free to re-open if you have any actionable items for us.

**Comment by 7h3h4ckv157** [comment]
Many thanks for the clarification. 
I'll detail the case publicly after I hear back from Google Bug Hunter Team. Let me confirm 🤝

Cheers,
