### ISSUE TITLE
Video Intelligence API Not Working

### ISSUE THREAD

**Issue by dsnair** [GoogleCloudPlatform/python-docs-samples#912]
Hello,

I followed the [instructions](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/video/cloud-client) to install the Video Intelligence API package. I was able to successfully use this package during the last couple weeks. However, starting yesterday, I've been having issues with being able to finish the API call. In fact, I can no longer finish running the following example code from the repo: `python analyze.py faces gs://demomaker/google_gmail.mp4`. It never goes past the while-loop and I eventually hit the API quota.

Has there been a recent update to this package? Thank you for taking the time to look into this.

Divya

**Comment by springml** [comment]
I am running into the same issue as well.  I tried executing the demo but it took more than 20 mins and all I see is the dots as shown below.  This same setup worked last week for me.

/python-docs-samples/video/cloud-client $ python analyze.py faces gs://demomaker/google_gmail.mp4
Processing video for label annotations:
...................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by jonparrott** [comment]
@gguuss can you take a look at this?

**Comment by gguuss** [comment]
I'm unable to reproduce this issue, I did the following:

```
git clone https://github.com/GoogleCloudPlatform/python-docs-samples
cd python-docs-samples/video/cloud-client
virtualenv env && source env/bin/activate
pip install -r requirements.txt
export export GOOGLE_APPLICATION_CREDENTIALS=/credentials/creds.json
python analyze.py faces gs://demomaker/google_gmail.mp4
```

Can you share more information about your configuration?  What OS are you using / what version of Python?

Is this specific to the parameters you're passing? Perhaps it's the length of the video or something to do with the GCS bucket you're using. Can you try the following shorter video with label annotations:

```
python analyze.py labels gs://demomaker/cat.mp4
```

**Comment by springml** [comment]
Unfortunately, this is not a consistent issue.  I am able to run the samples now but last night I was running into these issues.  It seemed like there was some kind of resource limits I reached which may be the root issue.

**Comment by gguuss** [comment]
Do you have multiple users on the same project?  I am seeing the following limits on quota:

https://cloud.google.com/video-intelligence/limits

With multiple users on the same account, it might be possible to hit those.

**Comment by gguuss** [comment]
Polling the long running operations counts towards your quota. This [poll request](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/920) updates the polling frequency in the sample. See if polling less frequently prevents this issue.

**Comment by boppyer** [comment]
I've got both the **labels** and **shots** examples working well. But I'm having problems with the face example. Which returns the following errors:

`Traceback (most recent call last):
  File "analyze.py", line 134, in <module>
    analyze_faces(args.path)
  File "analyze.py", line 38, in analyze_faces
    operation = video_client.annotate_video(path, features)
  File "/Users/bto01/.virtualenvs/googlevideo/lib/python2.7/site-packages/google/cloud/gapic/videointelligence/v1beta1/video_intelligence_service_client.py", line 234, in annotate_video
    self._annotate_video(request, options), self.operations_client,
  File "/Users/bto01/.virtualenvs/googlevideo/lib/python2.7/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "/Users/bto01/.virtualenvs/googlevideo/lib/python2.7/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "/Users/bto01/.virtualenvs/googlevideo/lib/python2.7/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "/Users/bto01/.virtualenvs/googlevideo/lib/python2.7/site-packages/google/gax/retry.py", line 126, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Request contains an invalid argument.)>)`

**Comment by dsnair** [comment]
I'm going to go ahead and close this issue! As @springml mentioned, the API behavior hasn't been consistent. Thankfully, I haven't seen that behavior in a while now and was able to complete the project. FYI, our project did have multiple users and the weird API behavior could have been because of the shared quota limits. Thank you for your time, gguss!
