### ISSUE TITLE
DLP sample tests need to be refactored

### ISSUE THREAD

**Issue by Sita04** [GoogleCloudPlatform/python-docs-samples#9186]
Currently DLP samples uses a hard-coded key and key ring. Additionally secrets wrapped with the key is also hard-coded into the test files. These need to be refactored so that resources can be created and deleted as part of the test lifecycle.
Related PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9091

**Comment by m-strzelczyk** [comment]
Note: keyrings and keys can't be really fully deleted, so it's ok to have some that are reused in tests. 

We still should use project specific resources if we use separate projects.

**Comment by BigBlackWolf** [comment]
As mentioned by @m-strzelczyk and according to the documentation, there is no way to delete the keyring.
The only way to "delete" a key is to disable all of its versions. However, the keys won't be removed entirely and will leave tombstones, which will persist indefinitely. Since those samples have only read operations with the keys, without any modifications, they won't generate many versions. Overall it appears to be efficient to have hard-coded values in this scenario, to properly utilize the resources.
