### ISSUE TITLE
Google Speech API - how to catch grpc errors and close recognition correctly in speechv1

### ISSUE THREAD

**Issue by datspike** [GoogleCloudPlatform/python-docs-samples#963]
Hello. While using speechv1beta I was able to catch grpc error such as OUT_OF_RANGE and others simply with 
```python
for resp in recognize_stream:
    if resp.error.code != code_pb2.OK:
        print(resp.error.message)
```
With introducing of speechv1 actual grpc resposces are getting handled inside the `speech` module, and I can only get `alternatives` 
```python
alternatives = self.audio_sample.streaming_recognize(self.language, interim_results=True,
                                                                 profanity_filter=True)
```

How can I catch grpc errors in new API?

The second question is how to stop the recognition correctly in the new API.
I can't find any fucntionality as 
```python
recognize_stream = service.StreamingRecognize(
                requests, self.DEADLINE_SECS)
...
recognize_stream.cancel()
```
in the new speechv1 api.
Thanks!

**Comment by jerjou** [comment]
Moved the issue to the google-cloud-python repo, since it's more a question about the client lib exposing these things, than the sample, per se. (ie I don't think the client lib exposes error handling hooks, judging by the [source](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/sample.py#L249))

Worst comes to worst, if you need finer-grained control than the more abstract client lib provides, you can always just use the lower-level [grpc lib](https://pypi.python.org/pypi/proto-google-cloud-speech-v1/0.15.3) that you used for the v1beta1 endpoint.
