### ISSUE TITLE
does cloud function triggered via pubsub require explicit acknowledgement?

### ISSUE THREAD

**Issue by gomrinal** [GoogleCloudPlatform/python-docs-samples#9920]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/43304bc95e0b2f0ac73fb061dff13d3d788a0b48/functions/v2/pubsub/main.py#L23

- I am consuming messages from cloud pub/sub in cloud function v2.  I follow the documentation approach however when I see my pubsub topic dashboard, the unacknowledged messages increases over time and oldest unacknowledged message time also increases linearly

**Comment by gomrinal** [comment]
For deploying CF, I used this:

```
gcloud functions deploy $CLOUD_FUNCTION_NAME \
--gen2 \
--region=$REGION  \
--runtime=$RUNTIME \
--source=$CF_LOCATION \
--entry-point=$ENTRY_POINT \
--trigger-topic=$PUBSUB_TOPIC \
--service-account=$SERVICE_ACCOUNT \
--run-service-account=$SERVICE_ACCOUNT
```

**Comment by gomrinal** [comment]
Also, to note here is that pub/sub topic has `pull` mechanism and while deploying I am specifying cloud function to use that pubsub topic.



However, I see that there's one automatic subscription created for that pubsub topic by `eventrac` which has `push` mode. Since, there is lack of clear documentation. I am getting confused that which subscription does cloud function consume based on a specified pubsub topic

**Comment by leahecole** [comment]
Reassigning to @engelke to triage within @GoogleCloudPlatform/torus-dpe

**Comment by engelke** [comment]
Hello, and thanks for this issue.

Issues for this repository are for reporting problems or feature requests, not for general questions about using them. StackOverflow is a good forum for dealing with these kinds of questions.

I can give a short answer to this one, though. This issue deals with the example at https://cloud.google.com/functions/docs/tutorials/pubsub. That example creates a Pub/Sub topic without overriding any default behaviors. That means that a pull subscription is automatically created for the topic at the same time. That pull subscription can be useful for examining what has been published to the topic.

However, that pull subscription is not what is triggering the function. That's a push subscription that is created when the function is deployed. The function does return a response, which acknowledged messages that trigger the function.

Since the pull subscription isn't being used, it will contain unacknowledged messages until they expire, so the number will usually grow.

I hope this is helpful.

**Comment by gomrinal** [comment]
Thanks @engelke that was helpful!
